---
- name: Create backup directory on host
  ansible.builtin.file:
    path: /opt/backups
    state: directory
    mode: '0755'

- name: Create backup script from template
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /usr/local/bin/devops-backup.sh
    mode: '0755'

- name: Schedule backup cron job
  ansible.builtin.cron:
    name: "Nusatech DevOps Stack Backup"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/devops-backup.sh"
    user: admin
  when: backup_enabled
